# snippet-start:[localstack.rust.use-localstack-cargo.toml]
[package]
name = "localstack-example"
version = "0.1.0"
authors = ["Doug Schwartz <dougsch@amazon.com>"]
edition = "2021"

[dependencies]
aws-config = { version = "1.0.1", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.4.0" }
aws-sdk-sqs = { version = "1.3.0" }
tokio = { version = "1.20.1", features = ["full"] }
http = "0.2"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
# snippet-end:[localstack.rust.use-localstack-cargo.toml]
